#!/bin/bash
echo -e '欢迎使用'
echo -e '正在加载，请稍后……'
termux-setup-storage
termux-wake-lock
echo -e '正在安装获取模拟权限，请稍后……'
pkg install proot git python screenfetch -y 
echo -e '正在安装Ubuntu，请稍后……'
git clone https://gitee.com/Le-niao/termux-install-linux.git 
cd termux-install-linux
python termux-linux-install.py
1
cd ~/Termux-Linux/Ubuntu && ./start-ubuntu.sh
curl -sL https://gitee.com/huifeidemangguomao/yunzai-one-button/raw/master/YZv3.sh | bash