#!/bin/bash

echo -e '欢迎使用'

echo -e '正在加载，请稍后……'

termux-setup-storage
termux-wake-lock

echo -e '正在安装获取模拟权限，请稍后……'

pkg install proot git python screenfetch -y 

echo -e '正在安装Ubuntu，请稍后……'

git clone https://gitee.com/Le-niao/termux-install-linux.git 

echo -e "\033[43;31m请输入阿拉伯数字1\033[0m"

cd termux-install-linux
python termux-linux-install.py
echo -e 'Ubuntu安装完毕'

apt update
apt install curl -y

echo -e "\033[32m接下来输入
curl -sL https://gitee.com/huifeidemangguomao/yunzai-one-button/raw/master/YZv3.sh | bash
继续安装:\033[0m"
echo -e '如果报错依次执行以下指令'
echo -e 'apt update'
echo -e 'apt install curl -y'
cd ~/Termux-Linux/Ubuntu
./start-ubuntu.sh
